/*
 * Headless check of the QR code library the pages load.
 *
 *   node preview/qrtest.js
 *
 * Shims just enough DOM for the SVG renderer, encodes a realistic client
 * configuration, and reports whether a QR code actually comes out and how big
 * it is. Browsers cannot be driven from here, so this is the closest thing to
 * proving the library works on the real page.
 */

const fs = require('fs');
const path = require('path');

// ------------------------------------------------------------------ DOM ---
function makeElement(tag) {
	return {
		tagName: tag,
		childNodes: [],
		attributes: {},
		style: {},
		get firstChild() { return this.childNodes[0] || null; },
		appendChild(child) { this.childNodes.push(child); return child; },
		removeChild(child) {
			const i = this.childNodes.indexOf(child);
			if (i >= 0) { this.childNodes.splice(i, 1); }
			return child;
		},
		setAttribute(name, value) { this.attributes[name] = String(value); },
		setAttributeNS(ns, name, value) { this.attributes[name] = String(value); },
		getAttribute(name) { return this.attributes[name]; },
		querySelector(sel) {
			if (this.tagName === sel) { return this; }
			for (const child of this.childNodes) {
				const hit = child.querySelector ? child.querySelector(sel) : null;
				if (hit) { return hit; }
			}
			return null;
		},
		set innerHTML(v) { this.childNodes = []; },
		get innerHTML() { return ''; }
	};
}

global.document = {
	createElement: makeElement,
	createElementNS: (ns, tag) => makeElement(tag)
};

global.XMLSerializer = function () {
	this.serializeToString = function serialize(node) {
		const attrs = Object.entries(node.attributes)
			.map(([k, v]) => ` ${k}="${v}"`).join('');
		const kids = node.childNodes.map(serialize).join('');
		return `<${node.tagName}${attrs}>${kids}</${node.tagName}>`;
	};
};

// ------------------------------------------------------------- the lib ---
const libPath = path.join(__dirname, '..', 'wgeasy', 'usr', 'local', 'www',
	'wgeasy', 'js', 'wgeasy_qrcode.js');

const source = fs.readFileSync(libPath, 'utf8');

// The file assigns to a bare `var QRCode`; evaluate it and hand it back
const QRCode = new Function(`${source}; return QRCode;`)();

// ---------------------------------------------------------------- test ---
function conf(bytes) {
	const base = [
		'# phone',
		'# Generated by pfsense on 2026-07-31 12:00:00',
		'# This file contains a private key. Keep it secret.',
		'',
		'[Interface]',
		'PrivateKey = uM3XE3a8egl2RLlyITTiVKcFZT1MStVKki6qLJl/ikY=',
		'Address = 10.6.0.3/32',
		'DNS = 10.6.0.1',
		'',
		'[Peer]',
		'PublicKey = kTMnLLLaBm81UZHliNwU8f6rkLJMbq26SpHBSn1FIRY=',
		'PresharedKey = sSLgd+X1POGMAx2PgcuWuPyaiDBEDfREjKqcglG6TLE=',
		'AllowedIPs = 10.6.0.0/24, 192.168.1.0/24',
		'Endpoint = vpn.example.com:51820',
		'PersistentKeepalive = 25',
		''
	].join('\n');

	if (!bytes) { return base; }

	// Pad with an extra allowed network to reach a target size
	let out = base;
	while (out.length < bytes) { out += '# padding padding padding padding\n'; }
	return out;
}

let pass = 0, fail = 0;

function check(label, ok, detail) {
	if (ok) { pass++; console.log(`  PASS  ${label}`); }
	else { fail++; console.log(`  FAIL  ${label}${detail ? `  (${detail})` : ''}`); }
}

console.log('\n== the library loads ==');

check('QRCode is a constructor', typeof QRCode === 'function');
check('it exposes CorrectLevel', QRCode && typeof QRCode.CorrectLevel === 'object');

console.log('\n== encoding a real client configuration ==');

const text = conf();

console.log(`  configuration is ${text.length} bytes`);

let qr = null, err = null;

try {
	qr = new QRCode(makeElement('div'), {
		text: text,
		width: 256,
		height: 256,
		correctLevel: QRCode.CorrectLevel.M
	});
} catch (e) {
	err = e;
}

check('a QR code is produced without throwing', err === null, err && err.message);

if (qr) {
	const svg = qr.toSVGString();

	check('it renders an SVG', typeof svg === 'string' && svg.startsWith('<svg'),
		svg ? svg.slice(0, 60) : 'empty');

	// The renderer emits one <use> per dark module, referencing a template rect
	const modules = (svg.match(/<use/g) || []).length;

	check('the SVG contains QR modules', modules > 100, `${modules} modules`);

	const viewBox = (svg.match(/viewBox="0 0 (\d+) \1"/) || [])[1];

	check('the viewBox is square and plausible for this payload',
		viewBox && (Number(viewBox) >= 21) && (Number(viewBox) <= 177), `viewBox 0 0 ${viewBox}`);

	const url = qr.toDataURL();

	check('toDataURL returns an SVG data URL',
		typeof url === 'string' && url.startsWith('data:image/svg+xml;base64,'),
		url ? url.slice(0, 40) : 'empty');

	/*
	 * Documented defect of the library, worked around by the pages: it ignores
	 * the width and height it is given and emits percentages, so the code has
	 * no size of its own and collapses in a container without a height.
	 */
	check('KNOWN: the library ignores the requested pixel size',
		svg.includes('width="100%"'), 'the pages must set width and height themselves');
}

console.log('\n== every error correction level ==');

for (const level of ['L', 'M', 'Q', 'H']) {
	let e = null;
	try {
		new QRCode(makeElement('div'), { text: text, correctLevel: QRCode.CorrectLevel[level] });
	} catch (ex) {
		e = ex;
	}
	check(`level ${level} encodes the configuration`, e === null, e && e.message);
}

console.log('\n== size limits ==');

for (const size of [200, 400, 800, 1200, 1600, 2000]) {
	let e = null;
	try {
		new QRCode(makeElement('div'), { text: conf(size), correctLevel: QRCode.CorrectLevel.M });
	} catch (ex) {
		e = ex;
	}
	check(`${size} byte configuration encodes at level M`, e === null, e && e.message);
}

console.log('\n== the fix the pages apply ==');

const QUIET = 4;

// Same helper the pages run after creating a code
function fixQrSvg(holder, size) {
	const svg = holder.querySelector('svg');

	if (!svg) { return null; }

	const box = (svg.getAttribute('viewBox') || '').split(/\s+/);
	const modules = (box.length === 4) ? parseInt(box[2], 10) : 0;

	if (modules > 0) {
		const side = modules + (QUIET * 2);

		svg.setAttribute('viewBox', `${-QUIET} ${-QUIET} ${side} ${side}`);

		for (const node of svg.childNodes) {
			if (node.tagName && (node.tagName.toLowerCase() === 'rect')) {
				node.setAttribute('x', -QUIET);
				node.setAttribute('y', -QUIET);
				node.setAttribute('width', side);
				node.setAttribute('height', side);
				break;
			}
		}
	}

	svg.setAttribute('width', size);
	svg.setAttribute('height', size);
	svg.setAttribute('style', 'max-width: 100%; height: auto;');

	if (!svg.getAttribute('xmlns')) {
		svg.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
	}

	return svg;
}

const holder = makeElement('div');

new QRCode(holder, { text: text, width: 512, height: 512, correctLevel: QRCode.CorrectLevel.M });

const fixed = fixQrSvg(holder, 512);

check('the svg element is found in the holder', fixed !== null);

if (fixed) {
	const out = new XMLSerializer().serializeToString(fixed);

	check('it now carries a pixel width and height',
		out.includes('width="512"') && out.includes('height="512"'));

	check('it declares the SVG namespace so it loads as an image',
		out.includes('xmlns="http://www.w3.org/2000/svg"'));

	check('the modules survived the fix', (out.match(/<use/g) || []).length > 100);

	check('it carries the quiet zone the standard requires',
		out.includes(`viewBox="${-QUIET} ${-QUIET} `), (out.match(/viewBox="[^"]*"/) || [])[0]);
}

/*
 * The real proof: rasterize what the pages produce and read it back with an
 * independent decoder. If this passes, a scanner is looking at the right bytes.
 */
console.log('\n== an independent decoder reads it back ==');

let jsQR = null;

try {
	jsQR = require('jsqr');
} catch (e) {
	console.log('  SKIP  jsqr is not installed, run: npm install --prefix preview');
}

function rasterize(holder, quiet, scale) {
	const svg = holder.querySelector('svg');
	const box = svg.getAttribute('viewBox').split(/\s+/).map(Number);

	// Module coordinates are independent of the viewBox origin
	const modules = box[2] - (quiet * 2);
	const side = (modules + quiet * 2) * scale;
	const data = new Uint8ClampedArray(side * side * 4).fill(255);

	for (const node of svg.childNodes) {
		if (node.tagName !== 'use') { continue; }

		const mx = Number(node.attributes.x);
		const my = Number(node.attributes.y);

		for (let dy = 0; dy < scale; dy++) {
			for (let dx = 0; dx < scale; dx++) {
				const i = (((my + quiet) * scale + dy) * side + ((mx + quiet) * scale + dx)) * 4;
				data[i] = data[i + 1] = data[i + 2] = 0;
			}
		}
	}

	return { data, side, modules };
}

if (jsQR) {
	for (const level of ['L', 'M']) {
		const h = makeElement('div');

		new QRCode(h, { text: text, correctLevel: QRCode.CorrectLevel[level] });

		fixQrSvg(h, 400);

		const { data, side, modules } = rasterize(h, QUIET, 4);
		const res = jsQR(data, side, side);

		check(`level ${level} decodes back to the exact configuration`,
			res !== null && res.data === text,
			res ? 'decoded but differs' : 'did not decode');

		if (level === 'L') {
			// What a phone camera has to resolve on screen
			const perModule = 400 / (modules + QUIET * 2);

			check('at the on screen size each module gets enough pixels',
				perModule >= 4, `${perModule.toFixed(2)} px per module over ${modules} modules`);
		}
	}
}

console.log(`\n${pass} passed, ${fail} failed\n`);

process.exit(fail > 0 ? 1 : 0);
